### ISSUE TITLE
On adding a template with inputs the inputs field is automatically expanded.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [bpmn-io/bpmn-properties-panel#184] opened 2021-11-18 15:25 UTC
__Describe the Bug__

On trying to add a new template that has error and input field the first input expands automatically  but not the error field.

__Steps to Reproduce__

1. Select a template that has input and error values to it.
2. We could see that just as we add the template to the service task the input field with its first input is automatically expanded and not the error in the error field.

__Expected Behavior__

The expansion of fields while adding a template should be aligned.

__Environment__

- OS: [ Windows 11]
- Library version: [4.11.1]

https://user-images.githubusercontent.com/85225325/142444168-9de3b254-0838-4a1d-8f97-801197a1b060.mp4

**Comment by pinussilvestrus** [comment] 2021-11-18 16:00
Related (or even a duplicate): https://github.com/bpmn-io/bpmn-properties-panel/issues/151

**Comment by barmac** [comment] 2021-11-18 20:02
Indeed this seems to be a duplicate of https://github.com/bpmn-io/bpmn-properties-panel/issues/151. Thanks for reporting anyway.

**Closed by barmac** 2021-11-18 20:02 UTC
Labels: bug
