### ISSUE TITLE
New properties panel sets wrong focus

### ISSUE THREAD

**Issue by volkergersabeck** [bpmn-io/bpmn-properties-panel#65] opened 2021-08-06 13:17 UTC
__Describe the Bug__

When a task has an extension property without a name
And I double click on the task to define the task label
Then the properties panel sets the focus on the extension property name
And I'm not changing the task label

![property panel focus issue](https://user-images.githubusercontent.com/232571/128516016-44e4540d-3eae-4db7-9773-91bccccce31c.gif)

__Expected Behavior__

Double click on a task always brings me to the mode where I can set the label, regardless of the state of its properties

__Environment__

Custom Modeler build for new properties panel in Platform

**Comment by pinussilvestrus** [comment] 2021-08-06 13:29
I was able to reproduce it on `main`. Looks a bit like the autofocus kicks in place (cf. https://github.com/bpmn-io/properties-panel/issues/63), so it might be fixed with https://github.com/bpmn-io/properties-panel/pull/89 + https://github.com/bpmn-io/bpmn-properties-panel/pull/63).

**Comment by MaxTru** [comment] 2021-08-10 06:32
I cannot reproduce this on Chrome running under Linux.

**Comment by MaxTru** [comment] 2021-08-24 08:40
@pinussilvestrus please have a second look

**Comment by pinussilvestrus** [comment] 2021-08-24 09:19
I double-checked it on the latest `main` and wasn't able to reproduce it anymore.

![Kapture 2021-08-24 at 11 16 50](https://user-images.githubusercontent.com/9433996/130591036-58aafab0-ffac-4732-a9e4-6730fe0ddde1.gif)

So it's probably resolved by the latest bug fixes (cf. https://github.com/bpmn-io/properties-panel/issues/63). It's not released yet though. Note that the item's open-state [does not get persisted](https://github.com/bpmn-io/properties-panel/issues/90) since the element selection changes on activating direct editing in bpmn-js.

**Closed** 2021-08-24 09:50 UTC
Labels: bug, ready
